# Generated by Django 5.1.3 on 2025-02-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='客户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=50, verbose_name='电话号码')),
                ('address', models.TextField(max_length=100, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(default=123456789, max_length=50, verbose_name='账号')),
                ('account_type', models.SmallIntegerField(choices=[(1, '活期'), (2, '定期')], default='1', verbose_name='账户类型')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer', verbose_name='客户ID')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.SmallIntegerField(choices=[(1, 'deposit'), (2, 'withdraw'), (3, 'transfer')], default=1, verbose_name='交易类型')),
                ('transaction_amount', models.IntegerField(default=0, verbose_name='交易金额')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_description', models.TextField(default='', max_length=100, verbose_name='交易描述')),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.account', verbose_name='账户ID')),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
            },
        ),
    ]
