# Generated by Django 5.1.3 on 2025-02-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(default=10000, verbose_name='账户余额'),
        ),
    ]
