# Generated by Django 5.1.3 on 2025-02-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_account_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
