# Generated by Django 5.1.3 on 2025-02-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_customer_id_account_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=123456789, max_length=50, unique=True, verbose_name='账号'),
        ),
    ]
