# Generated by Django 5.1.3 on 2025-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.SmallIntegerField(choices=[(1, '活期'), (2, '定期')], default=1, verbose_name='账户类型'),
        ),
    ]
