# Generated by Django 5.1.3 on 2025-03-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
